Repository finos/SwiftSearch, pull requests merged in 2019-06, with the labels that each got.

#23 aligning README.md and CONTRIBUTING.md to FINOS project blueprint language
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
  NOTICE
  README.md
Labels: cla-present

#24 SEARCH-1526 - Change logger implementation
  package.json
  src/compressionLib/compression.ts
  src/log/log.ts
  src/log/logLevels.ts
  src/log/logger.ts
  src/search.ts
  src/searchAPIBridge.ts
  src/utils/checkDiskSpace.ts
  src/utils/getCommandLineArgs.ts
  src/utils/misc.ts
  src/utils/queue.ts
  src/utils/searchUtils.ts
Labels: cla-present, ✨enhancement

#22 feat: SEARCH-1514 - Include Index-Validator for verifying the index
  package.json
  src/interface/interface.ts
  src/search.ts
  src/searchAPIBridge.ts
  src/searchConfig.ts
  tests/Search.test.ts
  tests/SearchContextIsolation.test.ts
Labels: :trophy: master, cla-present, unit-tests, ✨enhancement

#25 Revert ffi napi
  .gitignore
  package.json
  src/search.ts
  src/searchLibrary.ts
Labels: cla-present

#26 SEARCH-1527 - Display swift-search version details in the More Info
  package.json
  src/search.ts
  src/searchAPIBridge.ts
  src/utils/searchUtils.ts
Labels: :trophy: master, cla-present, ✨enhancement

#27 feat: SEARCH-1541 - Change FreeDiskSpace to use native binding
  package.json
  src/interface/interface.ts
  src/search.ts
  src/searchAPIBridge.ts
  src/searchConfig.ts
  src/utils/checkDiskSpace.ts
  src/utils/searchUtils.ts
  tests/Search.test.ts
Labels: :trophy: master, cla-present, ✨enhancement

#28 feat: SEARCH-1562 - Check Index File Size Before Initializing Swift Search
  package.json
  src/interface/interface.ts
  src/search.ts
  src/searchAPIBridge.ts
  src/utils/searchUtils.ts
Labels: :control_knobs: context-isolation, :trophy: master, cla-present, ✨enhancement
